apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: nodeip-controller
    app.kubernetes.io/part-of: nodeip-controller
    app.kubernetes.io/managed-by: kustomize
  annotations:
    iam.gke.io/gcp-service-account: GCP_SA
  name: controller-manager
  namespace: system
